export interface ServiceFAQ {
  q: { ar: string; en: string };
  a: { ar: string; en: string };
}

export interface Service {
  slug: string;
  category: string;
  icon: string;
  title: { ar: string; en: string };
  metaTitle: { ar: string; en: string };
  metaDesc: { ar: string; en: string };
  h1: { ar: string; en: string };
  description: { ar: string; en: string };
  features: { ar: string; en: string }[];
  faqs: ServiceFAQ[];
}

export const services: Service[] = [
  {
    slug: "web-design-companies-egypt",
    category: "web-design",
    icon: "Globe",
    title: { ar: "شركات إنشاء وتصميم مواقع في مصر", en: "Web Design Companies in Egypt" },
    metaTitle: { ar: "أفضل شركات إنشاء وتصميم مواقع في مصر 2026", en: "Best Web Design Companies in Egypt 2026 | Professional Design" },
    metaDesc: { ar: "اكتشف أفضل شركات إنشاء وتصميم المواقع في مصر. نقدم تصميمات مبتكرة ومتجاوبة تساعد عملك على النمو. احصل على عرض سعر مجاني.", en: "Discover the best web design companies in Egypt. We deliver innovative, responsive designs that help your business grow. Get a free quote now." },
    h1: { ar: "أفضل شركة إنشاء وتصميم مواقع إلكترونية في مصر", en: "Top Web Design Company in Egypt" },
    description: { ar: "نحن شركة رائدة في تصميم المواقع الإلكترونية في مصر، نقدم حلولاً رقمية مبتكرة تجمع بين الجمال والأداء العالي. فريقنا المتخصص يعمل على تصميم مواقع متجاوبة ومحسّنة لمحركات البحث تساعد عملك على التميز في السوق الرقمي المصري. نستخدم أحدث التقنيات وأفضل الممارسات لضمان تجربة مستخدم استثنائية على جميع الأجهزة.", en: "We are a leading web design company in Egypt, delivering innovative digital solutions that combine beauty and high performance. Our specialized team creates responsive, SEO-optimized websites that help your business stand out in the Egyptian digital market. We use the latest technologies and best practices to ensure exceptional user experience across all devices." },
    features: [
      { ar: "تصميم متجاوب مع جميع الأجهزة", en: "Responsive design for all devices" },
      { ar: "تحسين محركات البحث SEO", en: "SEO optimization" },
      { ar: "تصميم واجهة مستخدم حديثة", en: "Modern UI/UX design" },
      { ar: "سرعة تحميل فائقة", en: "Lightning-fast loading speed" },
    ],
    faqs: [
      { q: { ar: "كم تكلفة تصميم موقع في مصر؟", en: "How much does web design cost in Egypt?" }, a: { ar: "تختلف التكلفة حسب متطلبات المشروع، تبدأ من أسعار تنافسية مع جودة عالية. تواصل معنا للحصول على عرض سعر مخصص.", en: "Costs vary based on project requirements, starting at competitive prices with high quality. Contact us for a custom quote." } },
      { q: { ar: "كم يستغرق تصميم الموقع؟", en: "How long does web design take?" }, a: { ar: "عادة ما يستغرق التصميم من 2 إلى 6 أسابيع حسب حجم المشروع ومتطلباته.", en: "Design typically takes 2 to 6 weeks depending on project size and requirements." } },
      { q: { ar: "هل تقدمون خدمات الدعم بعد التسليم؟", en: "Do you offer post-delivery support?" }, a: { ar: "نعم، نقدم دعمًا فنيًا مستمرًا وصيانة دورية لضمان عمل موقعك بأفضل أداء.", en: "Yes, we provide continuous technical support and regular maintenance to ensure optimal performance." } },
    ],
  },
  {
    slug: "ecommerce-store-egypt",
    category: "web-design",
    icon: "ShoppingCart",
    title: { ar: "إنشاء وتصميم متجر إلكتروني في مصر", en: "E-commerce Store Design in Egypt" },
    metaTitle: { ar: "إنشاء وتصميم متجر إلكتروني احترافي في مصر", en: "Professional E-commerce Store Design in Egypt | Online Stores" },
    metaDesc: { ar: "احصل على متجر إلكتروني احترافي متكامل مع بوابات الدفع وإدارة المخزون. أفضل حلول التجارة الإلكترونية في مصر.", en: "Get a professional, fully-integrated e-commerce store with payment gateways and inventory management. Best e-commerce solutions in Egypt." },
    h1: { ar: "إنشاء وتصميم متجر إلكتروني متكامل في مصر", en: "Complete E-commerce Store Design in Egypt" },
    description: { ar: "نصمم متاجر إلكترونية احترافية متكاملة مع بوابات الدفع الإلكتروني وأنظمة إدارة المخزون. نوفر حلول تجارة إلكترونية متقدمة تساعدك على بيع منتجاتك عبر الإنترنت بسهولة وأمان. متاجرنا مصممة لتحقيق أعلى معدلات التحويل وزيادة مبيعاتك.", en: "We design professional, fully-integrated e-commerce stores with payment gateways and inventory management systems. We provide advanced e-commerce solutions that help you sell your products online easily and securely. Our stores are designed to achieve the highest conversion rates and increase your sales." },
    features: [
      { ar: "بوابات دفع متعددة", en: "Multiple payment gateways" },
      { ar: "إدارة مخزون متقدمة", en: "Advanced inventory management" },
      { ar: "تصميم محسن للتحويلات", en: "Conversion-optimized design" },
      { ar: "لوحة تحكم سهلة الاستخدام", en: "Easy-to-use dashboard" },
    ],
    faqs: [
      { q: { ar: "ما هي أفضل منصة لبناء متجر إلكتروني؟", en: "What's the best platform for an e-commerce store?" }, a: { ar: "نختار المنصة الأنسب لاحتياجاتك سواء كانت ووردبريس، شوبيفاي، أو حل مخصص.", en: "We choose the most suitable platform for your needs, whether WordPress, Shopify, or a custom solution." } },
      { q: { ar: "هل يدعم المتجر الدفع الإلكتروني؟", en: "Does the store support online payments?" }, a: { ar: "نعم، ندمج جميع بوابات الدفع الشائعة في مصر مثل فوري وفيزا وماستركارد.", en: "Yes, we integrate all popular payment gateways in Egypt including Fawry, Visa, and Mastercard." } },
      { q: { ar: "هل يمكنني إدارة المتجر بنفسي؟", en: "Can I manage the store myself?" }, a: { ar: "بالتأكيد، نوفر لوحة تحكم سهلة مع تدريب كامل على إدارة المنتجات والطلبات.", en: "Absolutely, we provide an easy dashboard with full training on managing products and orders." } },
    ],
  },
  {
    slug: "seo-services-egypt",
    category: "marketing",
    icon: "Search",
    title: { ar: "خدمات تحسين محركات البحث في مصر", en: "SEO Services in Egypt" },
    metaTitle: { ar: "خدمات SEO في مصر | تحسين محركات البحث", en: "SEO Services in Egypt | Search Engine Optimization" },
    metaDesc: { ar: "خدمات تحسين محركات البحث الاحترافية في مصر. نساعدك على تصدر نتائج جوجل وزيادة الزيارات العضوية لموقعك.", en: "Professional SEO services in Egypt. We help you rank first on Google and increase organic traffic to your website." },
    h1: { ar: "خدمات تحسين محركات البحث الاحترافية في مصر", en: "Professional SEO Services in Egypt" },
    description: { ar: "نقدم خدمات تحسين محركات البحث المتقدمة التي تساعد موقعك على تصدر نتائج البحث في جوجل. فريقنا المتخصص يستخدم أحدث استراتيجيات SEO لزيادة الزيارات العضوية وتحسين ظهور علامتك التجارية على الإنترنت.", en: "We provide advanced SEO services that help your website rank at the top of Google search results. Our specialized team uses the latest SEO strategies to increase organic traffic and improve your brand's online visibility." },
    features: [
      { ar: "تحليل الكلمات المفتاحية", en: "Keyword research & analysis" },
      { ar: "تحسين المحتوى والصفحات", en: "On-page optimization" },
      { ar: "بناء الروابط الخلفية", en: "Link building" },
      { ar: "تقارير أداء شهرية", en: "Monthly performance reports" },
    ],
    faqs: [
      { q: { ar: "متى تظهر نتائج SEO؟", en: "When do SEO results appear?" }, a: { ar: "عادة ما تبدأ النتائج بالظهور خلال 3 إلى 6 أشهر من بدء العمل.", en: "Results typically start appearing within 3 to 6 months of starting work." } },
      { q: { ar: "هل يمكن ضمان المركز الأول في جوجل؟", en: "Can you guarantee the first position on Google?" }, a: { ar: "لا يمكن ضمان ذلك بشكل مطلق، لكننا نضمن تحسينات ملموسة في ترتيب موقعك.", en: "No one can absolutely guarantee that, but we ensure tangible improvements in your ranking." } },
      { q: { ar: "ما الفرق بين SEO والإعلانات المدفوعة؟", en: "What's the difference between SEO and paid ads?" }, a: { ar: "SEO يوفر نتائج مستدامة طويلة المدى بينما الإعلانات توفر نتائج فورية مؤقتة.", en: "SEO provides sustainable long-term results while ads provide immediate but temporary results." } },
    ],
  },
  {
    slug: "real-estate-website-design",
    category: "industry",
    icon: "Building2",
    title: { ar: "إنشاء وتصميم موقع عقارات", en: "Real Estate Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع عقارات احترافي في مصر", en: "Professional Real Estate Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع عقارية احترافية مع نظام بحث متقدم وعرض العقارات بشكل جذاب. الحل الأمثل لشركات العقارات في مصر.", en: "Professional real estate website design with advanced search and attractive property listings. The ideal solution for real estate companies in Egypt." },
    h1: { ar: "إنشاء وتصميم مواقع عقارية احترافية في مصر", en: "Professional Real Estate Website Design in Egypt" },
    description: { ar: "نصمم مواقع عقارية متطورة مع نظام بحث متقدم عن العقارات، خرائط تفاعلية، وعرض احترافي للوحدات العقارية. مواقعنا العقارية تساعد شركات العقارات على عرض مشاريعها بشكل جذاب وجلب عملاء جدد.", en: "We design advanced real estate websites with advanced property search, interactive maps, and professional property listings. Our real estate sites help companies showcase projects attractively and attract new clients." },
    features: [
      { ar: "نظام بحث متقدم عن العقارات", en: "Advanced property search system" },
      { ar: "خرائط تفاعلية", en: "Interactive maps" },
      { ar: "جولات افتراضية 360°", en: "360° virtual tours" },
      { ar: "نظام حجز المواعيد", en: "Appointment booking system" },
    ],
    faqs: [
      { q: { ar: "هل يمكن إضافة عقارات بسهولة؟", en: "Can I easily add properties?" }, a: { ar: "نعم، نوفر لوحة تحكم سهلة لإدارة العقارات وإضافتها وتعديلها.", en: "Yes, we provide an easy dashboard to manage, add, and edit properties." } },
      { q: { ar: "هل الموقع يدعم البحث المتقدم؟", en: "Does the site support advanced search?" }, a: { ar: "نعم، مع فلاتر متعددة مثل المنطقة والسعر والمساحة ونوع العقار.", en: "Yes, with multiple filters like area, price, size, and property type." } },
      { q: { ar: "هل يمكن ربط الموقع بـ CRM؟", en: "Can the site integrate with CRM?" }, a: { ar: "بالتأكيد، نوفر تكامل مع أنظمة CRM لإدارة العملاء والمبيعات.", en: "Absolutely, we provide CRM integration for client and sales management." } },
    ],
  },
  {
    slug: "medical-website-design",
    category: "industry",
    icon: "Heart",
    title: { ar: "إنشاء وتصميم موقع طبي", en: "Medical Website Design" },
    metaTitle: { ar: "إنشاء وتصميم مواقع طبية احترافية في مصر", en: "Professional Medical Website Design in Egypt | Doctor & Clinic Sites" },
    metaDesc: { ar: "إنشاء وتصميم مواقع طبية احترافية للأطباء والعيادات والمستشفيات في مصر مع نظام حجز مواعيد متكامل.", en: "Professional medical website design for doctors, clinics, and hospitals in Egypt with integrated appointment booking." },
    h1: { ar: "إنشاء وتصميم مواقع طبية متخصصة في مصر", en: "Specialized Medical Website Design in Egypt" },
    description: { ar: "نصمم مواقع طبية احترافية للأطباء والعيادات والمستشفيات مع أنظمة حجز المواعيد الإلكترونية. مواقعنا الطبية مصممة لبناء الثقة مع المرضى وتسهيل الوصول إلى خدماتك الطبية.", en: "We design professional medical websites for doctors, clinics, and hospitals with online appointment booking systems. Our medical sites are designed to build trust with patients and facilitate access to your medical services." },
    features: [
      { ar: "نظام حجز مواعيد إلكتروني", en: "Online appointment booking" },
      { ar: "ملفات تعريف الأطباء", en: "Doctor profiles" },
      { ar: "قسم المقالات الطبية", en: "Medical articles section" },
      { ar: "تصميم يبني الثقة", en: "Trust-building design" },
    ],
    faqs: [
      { q: { ar: "هل الموقع يتوافق مع معايير المواقع الطبية؟", en: "Does the site comply with medical website standards?" }, a: { ar: "نعم، نلتزم بأفضل المعايير والممارسات في تصميم المواقع الطبية.", en: "Yes, we adhere to the best standards and practices in medical web design." } },
      { q: { ar: "هل يمكن للمرضى حجز مواعيد أونلاين؟", en: "Can patients book appointments online?" }, a: { ar: "نعم، نوفر نظام حجز مواعيد إلكتروني متكامل وسهل الاستخدام.", en: "Yes, we provide a fully integrated and easy-to-use online booking system." } },
      { q: { ar: "هل يدعم الموقع عدة أطباء؟", en: "Does the site support multiple doctors?" }, a: { ar: "نعم، يمكن إضافة عدد غير محدود من الأطباء مع صفحات تعريفية لكل طبيب.", en: "Yes, unlimited doctors can be added with profile pages for each." } },
    ],
  },
  {
    slug: "dental-clinic-website-design",
    category: "industry",
    icon: "Smile",
    title: { ar: "إنشاء وتصميم موقع عيادة أسنان", en: "Dental Clinic Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع عيادة أسنان في مصر", en: "Dental Clinic Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم موقع احترافي لعيادة الأسنان مع نظام حجز مواعيد وعرض الخدمات. جذب مرضى جدد عبر الإنترنت.", en: "Professional dental clinic website with appointment booking and services display. Attract new patients online." },
    h1: { ar: "إنشاء وتصميم مواقع عيادات الأسنان في مصر", en: "Dental Clinic Website Design in Egypt" },
    description: { ar: "نصمم مواقع احترافية لعيادات الأسنان تعرض خدماتك بشكل جذاب وتجذب مرضى جدد. مع نظام حجز مواعيد وقبل وبعد العلاج.", en: "We design professional dental clinic websites that showcase your services attractively and attract new patients. With appointment booking and before/after treatment galleries." },
    features: [
      { ar: "معرض صور قبل وبعد العلاج", en: "Before/after treatment gallery" },
      { ar: "نظام حجز مواعيد", en: "Appointment booking system" },
      { ar: "عرض الخدمات والأسعار", en: "Services & pricing display" },
      { ar: "تقييمات المرضى", en: "Patient reviews" },
    ],
    faqs: [
      { q: { ar: "هل يمكن عرض صور قبل وبعد العلاج؟", en: "Can I show before/after photos?" }, a: { ar: "نعم، نوفر معرض صور احترافي لعرض نتائج العلاج.", en: "Yes, we provide a professional gallery to showcase treatment results." } },
      { q: { ar: "هل يدعم الموقع الحجز الأونلاين؟", en: "Does the site support online booking?" }, a: { ar: "نعم، مع إشعارات تلقائية للطبيب والمريض.", en: "Yes, with automatic notifications for both doctor and patient." } },
      { q: { ar: "هل يمكن إضافة مدونة طبية؟", en: "Can I add a medical blog?" }, a: { ar: "نعم، المدونة تساعد في تحسين SEO وتثقيف المرضى.", en: "Yes, a blog helps improve SEO and educate patients." } },
    ],
  },
  {
    slug: "corporate-website-design",
    category: "web-design",
    icon: "Briefcase",
    title: { ar: "إنشاء وتصميم موقع شركة", en: "Corporate Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع شركة احترافي في مصر", en: "Professional Corporate Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع شركات احترافية تعكس هوية علامتك التجارية وتبني الثقة مع عملائك في مصر.", en: "Professional corporate website design that reflects your brand identity and builds trust with your clients in Egypt." },
    h1: { ar: "إنشاء وتصميم مواقع الشركات الاحترافية في مصر", en: "Professional Corporate Website Design in Egypt" },
    description: { ar: "نصمم مواقع شركات احترافية تعكس قوة وهوية علامتك التجارية. مواقعنا تساعد الشركات على بناء حضور رقمي قوي وجذب عملاء جدد من خلال تصميم عصري ومحتوى مقنع.", en: "We design professional corporate websites that reflect the strength and identity of your brand. Our sites help companies build a strong digital presence and attract new clients through modern design and compelling content." },
    features: [
      { ar: "تصميم يعكس هوية الشركة", en: "Design reflecting company identity" },
      { ar: "صفحات الخدمات والمنتجات", en: "Services & products pages" },
      { ar: "قسم الأخبار والمدونة", en: "News & blog section" },
      { ar: "نموذج تواصل متقدم", en: "Advanced contact form" },
    ],
    faqs: [
      { q: { ar: "هل يمكنكم تصميم موقع بعدة لغات؟", en: "Can you design a multilingual website?" }, a: { ar: "نعم، نصمم مواقع متعددة اللغات مع دعم كامل للعربية والإنجليزية.", en: "Yes, we design multilingual websites with full Arabic and English support." } },
      { q: { ar: "هل تقدمون خدمات التصوير؟", en: "Do you offer photography services?" }, a: { ar: "نعم، يمكننا توفير تصوير احترافي لشركتك ومنتجاتك.", en: "Yes, we can provide professional photography for your company and products." } },
      { q: { ar: "كيف يمكنني تحديث محتوى الموقع؟", en: "How can I update website content?" }, a: { ar: "نوفر لوحة تحكم سهلة تمكنك من تحديث المحتوى بنفسك.", en: "We provide an easy dashboard that allows you to update content yourself." } },
    ],
  },
  {
    slug: "landing-page-design",
    category: "web-design",
    icon: "Rocket",
    title: { ar: "إنشاء وتصميم صفحة هبوط", en: "Landing Page Design" },
    metaTitle: { ar: "إنشاء وتصميم صفحة هبوط احترافية في مصر", en: "Professional Landing Page Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم صفحات هبوط عالية التحويل لحملاتك الإعلانية. زيادة معدل التحويل وجذب المزيد من العملاء.", en: "High-converting landing page design for your ad campaigns. Increase conversion rates and attract more clients." },
    h1: { ar: "إنشاء وتصميم صفحات هبوط عالية التحويل", en: "High-Converting Landing Page Design" },
    description: { ar: "نصمم صفحات هبوط احترافية محسّنة لتحقيق أعلى معدلات التحويل. صفحاتنا مصممة خصيصًا لحملاتك الإعلانية على جوجل وفيسبوك لتحويل الزوار إلى عملاء.", en: "We design professional landing pages optimized for highest conversion rates. Our pages are specially designed for your Google and Facebook ad campaigns to convert visitors into clients." },
    features: [
      { ar: "تصميم محسّن للتحويلات", en: "Conversion-optimized design" },
      { ar: "اختبار A/B", en: "A/B testing" },
      { ar: "سرعة تحميل فائقة", en: "Ultra-fast loading" },
      { ar: "تكامل مع أدوات التحليل", en: "Analytics integration" },
    ],
    faqs: [
      { q: { ar: "ما الفرق بين صفحة الهبوط والموقع العادي؟", en: "What's the difference between a landing page and a regular site?" }, a: { ar: "صفحة الهبوط مصممة لهدف واحد محدد مثل جمع بيانات العملاء أو البيع.", en: "A landing page is designed for one specific goal like lead capture or sales." } },
      { q: { ar: "هل يمكن ربطها بحملات الإعلانات؟", en: "Can it be linked to ad campaigns?" }, a: { ar: "نعم، نصممها خصيصًا لتعمل مع حملات جوجل وفيسبوك.", en: "Yes, we design them specifically to work with Google and Facebook campaigns." } },
      { q: { ar: "كم معدل التحويل المتوقع؟", en: "What's the expected conversion rate?" }, a: { ar: "صفحاتنا تحقق معدلات تحويل من 5% إلى 25% حسب المجال.", en: "Our pages achieve conversion rates from 5% to 25% depending on the industry." } },
    ],
  },
  {
    slug: "personal-portfolio-website",
    category: "web-design",
    icon: "User",
    title: { ar: "إنشاء وتصميم موقع شخصي", en: "Personal Portfolio Website" },
    metaTitle: { ar: "إنشاء وتصميم موقع شخصي احترافي", en: "Professional Personal Portfolio Website Design" },
    metaDesc: { ar: "إنشاء وتصميم موقع شخصي احترافي يعرض أعمالك ومهاراتك بشكل مبهر. اصنع بصمتك الرقمية.", en: "Professional personal portfolio website showcasing your work and skills impressively. Make your digital mark." },
    h1: { ar: "إنشاء وتصميم موقع بورتفوليو شخصي احترافي", en: "Professional Personal Portfolio Website Design" },
    description: { ar: "نصمم مواقع شخصية احترافية تعرض أعمالك ومهاراتك وإنجازاتك بشكل مبهر. موقعك الشخصي هو بطاقتك الرقمية التي تميزك عن الآخرين.", en: "We design professional personal websites that showcase your work, skills, and achievements impressively. Your personal site is your digital business card that sets you apart." },
    features: [
      { ar: "معرض أعمال تفاعلي", en: "Interactive work gallery" },
      { ar: "سيرة ذاتية رقمية", en: "Digital resume" },
      { ar: "تصميم فريد ومميز", en: "Unique custom design" },
      { ar: "نموذج تواصل مباشر", en: "Direct contact form" },
    ],
    faqs: [
      { q: { ar: "هل يمكنني تحديث الأعمال بنفسي؟", en: "Can I update my portfolio myself?" }, a: { ar: "نعم، نوفر لك طريقة سهلة لإضافة وتعديل أعمالك.", en: "Yes, we provide an easy way to add and edit your work." } },
      { q: { ar: "هل يمكن إضافة مدونة؟", en: "Can I add a blog?" }, a: { ar: "نعم، المدونة تساعد في إبراز خبراتك وتحسين ظهور موقعك.", en: "Yes, a blog helps showcase your expertise and improve site visibility." } },
      { q: { ar: "هل الموقع متجاوب مع الهواتف؟", en: "Is the site mobile responsive?" }, a: { ar: "بالتأكيد، جميع مواقعنا متجاوبة تمامًا مع جميع الأجهزة.", en: "Absolutely, all our sites are fully responsive across all devices." } },
    ],
  },
  {
    slug: "restaurant-website-design",
    category: "industry",
    icon: "UtensilsCrossed",
    title: { ar: "إنشاء وتصميم موقع مطعم", en: "Restaurant Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع مطعم احترافي في مصر", en: "Professional Restaurant Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع مطاعم جذابة مع قوائم طعام تفاعلية ونظام طلب أونلاين. اجذب المزيد من الزبائن.", en: "Attractive restaurant website design with interactive menus and online ordering. Attract more customers." },
    h1: { ar: "إنشاء وتصميم مواقع المطاعم والكافيهات في مصر", en: "Restaurant & Café Website Design in Egypt" },
    description: { ar: "نصمم مواقع مطاعم جذابة تفتح شهية زوارك قبل وصولهم. مع قوائم طعام تفاعلية، نظام حجز طاولات، وإمكانية الطلب أونلاين.", en: "We design attractive restaurant websites that whet visitors' appetites before they arrive. With interactive menus, table reservation, and online ordering." },
    features: [
      { ar: "قائمة طعام تفاعلية", en: "Interactive food menu" },
      { ar: "نظام حجز طاولات", en: "Table reservation system" },
      { ar: "طلب أونلاين", en: "Online ordering" },
      { ar: "معرض صور الأطباق", en: "Dish photo gallery" },
    ],
    faqs: [
      { q: { ar: "هل يمكنني تحديث قائمة الطعام بسهولة؟", en: "Can I easily update the menu?" }, a: { ar: "نعم، من خلال لوحة تحكم بسيطة يمكنك تعديل الأصناف والأسعار.", en: "Yes, through a simple dashboard you can modify items and prices." } },
      { q: { ar: "هل يدعم الطلب الأونلاين؟", en: "Does it support online ordering?" }, a: { ar: "نعم، مع إشعارات فورية للمطبخ وتتبع الطلبات.", en: "Yes, with instant kitchen notifications and order tracking." } },
      { q: { ar: "هل يمكن ربطه بتطبيقات التوصيل؟", en: "Can it integrate with delivery apps?" }, a: { ar: "نعم، نوفر تكامل مع منصات التوصيل المختلفة.", en: "Yes, we provide integration with various delivery platforms." } },
    ],
  },
  {
    slug: "school-website-design",
    category: "industry",
    icon: "GraduationCap",
    title: { ar: "إنشاء وتصميم موقع مدرسة", en: "School Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع مدرسة احترافي في مصر", en: "Professional School Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع مدارس احترافية مع بوابة أولياء الأمور ونظام إدارة المحتوى التعليمي.", en: "Professional school website design with parent portal and educational content management." },
    h1: { ar: "إنشاء وتصميم مواقع المدارس والمؤسسات التعليمية", en: "School & Educational Institution Website Design" },
    description: { ar: "نصمم مواقع تعليمية شاملة للمدارس والجامعات مع بوابة أولياء أمور وأنظمة إدارة المحتوى التعليمي.", en: "We design comprehensive educational websites for schools and universities with parent portals and content management systems." },
    features: [
      { ar: "بوابة أولياء الأمور", en: "Parent portal" },
      { ar: "نظام إدارة المحتوى", en: "Content management system" },
      { ar: "جدول الحصص", en: "Class schedule" },
      { ar: "نظام التقديم الإلكتروني", en: "Online admission system" },
    ],
    faqs: [
      { q: { ar: "هل يمكن لأولياء الأمور متابعة أبنائهم؟", en: "Can parents track their children's progress?" }, a: { ar: "نعم، من خلال بوابة مخصصة لأولياء الأمور.", en: "Yes, through a dedicated parent portal." } },
      { q: { ar: "هل يدعم التقديم الإلكتروني؟", en: "Does it support online admissions?" }, a: { ar: "نعم، مع نماذج تقديم متكاملة وإدارة الطلبات.", en: "Yes, with complete application forms and request management." } },
      { q: { ar: "هل يمكن نشر الأخبار والأنشطة؟", en: "Can we publish news and activities?" }, a: { ar: "نعم، مع قسم أخبار وأنشطة متكامل.", en: "Yes, with a complete news and activities section." } },
    ],
  },
  {
    slug: "tourism-website-design",
    category: "industry",
    icon: "Plane",
    title: { ar: "إنشاء وتصميم موقع سياحي", en: "Tourism Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع سياحي في مصر", en: "Tourism Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع سياحية جذابة مع نظام حجز الرحلات والفنادق. اجذب السياح من جميع أنحاء العالم.", en: "Attractive tourism website design with trip and hotel booking. Attract tourists from around the world." },
    h1: { ar: "إنشاء وتصميم مواقع شركات السياحة والسفر", en: "Tourism & Travel Company Website Design" },
    description: { ar: "نصمم مواقع سياحية تعرض وجهاتك ورحلاتك بشكل مبهر مع نظام حجز متكامل.", en: "We design tourism websites that showcase your destinations and trips impressively with integrated booking." },
    features: [
      { ar: "نظام حجز رحلات", en: "Trip booking system" },
      { ar: "عرض الوجهات السياحية", en: "Tourist destinations showcase" },
      { ar: "معرض صور ومقاطع فيديو", en: "Photo & video gallery" },
      { ar: "تقييمات العملاء", en: "Customer reviews" },
    ],
    faqs: [
      { q: { ar: "هل يدعم الحجز الأونلاين؟", en: "Does it support online booking?" }, a: { ar: "نعم، مع نظام حجز متكامل ودفع إلكتروني.", en: "Yes, with integrated booking and online payment." } },
      { q: { ar: "هل يمكن عرض الرحلات بعدة لغات؟", en: "Can trips be displayed in multiple languages?" }, a: { ar: "نعم، ندعم عدة لغات لاستهداف السياح الدوليين.", en: "Yes, we support multiple languages for international tourists." } },
      { q: { ar: "هل يمكن ربطه بمواقع الحجز العالمية؟", en: "Can it integrate with global booking sites?" }, a: { ar: "نعم، نوفر تكامل مع منصات الحجز المختلفة.", en: "Yes, we provide integration with various booking platforms." } },
    ],
  },
  {
    slug: "law-firm-website-design",
    category: "industry",
    icon: "Scale",
    title: { ar: "إنشاء وتصميم موقع مكتب محاماة", en: "Law Firm Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع مكتب محاماة في مصر", en: "Law Firm Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع احترافية لمكاتب المحاماة والمستشارين القانونيين. بناء الثقة وجذب العملاء.", en: "Professional website design for law firms and legal consultants. Build trust and attract clients." },
    h1: { ar: "إنشاء وتصميم مواقع مكاتب المحاماة والاستشارات القانونية", en: "Law Firm & Legal Consultation Website Design" },
    description: { ar: "نصمم مواقع احترافية لمكاتب المحاماة تعكس الاحترافية والثقة وتساعد في جذب عملاء جدد.", en: "We design professional law firm websites that reflect professionalism and trust, helping attract new clients." },
    features: [
      { ar: "صفحات التخصصات القانونية", en: "Legal specialty pages" },
      { ar: "نظام استشارة أونلاين", en: "Online consultation system" },
      { ar: "ملفات تعريف المحامين", en: "Lawyer profiles" },
      { ar: "مدونة قانونية", en: "Legal blog" },
    ],
    faqs: [
      { q: { ar: "هل يمكن حجز استشارة أونلاين؟", en: "Can clients book online consultations?" }, a: { ar: "نعم، مع نظام حجز مواعيد وإمكانية الاستشارة عن بعد.", en: "Yes, with appointment booking and remote consultation capability." } },
      { q: { ar: "هل يمكن نشر مقالات قانونية؟", en: "Can we publish legal articles?" }, a: { ar: "نعم، المدونة القانونية تساعد في تحسين SEO وبناء السمعة.", en: "Yes, a legal blog helps improve SEO and build reputation." } },
      { q: { ar: "هل التصميم يبني الثقة؟", en: "Does the design build trust?" }, a: { ar: "نعم، نستخدم تصميمات تعكس الاحترافية والمصداقية.", en: "Yes, we use designs that reflect professionalism and credibility." } },
    ],
  },
  {
    slug: "construction-company-website",
    category: "industry",
    icon: "Hammer",
    title: { ar: "إنشاء وتصميم موقع شركة مقاولات", en: "Construction Company Website" },
    metaTitle: { ar: "إنشاء وتصميم موقع شركة مقاولات في مصر", en: "Construction Company Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع احترافية لشركات المقاولات والبناء مع معرض مشاريع تفاعلي.", en: "Professional website design for construction and building companies with interactive project gallery." },
    h1: { ar: "إنشاء وتصميم مواقع شركات المقاولات والبناء", en: "Construction & Building Company Website Design" },
    description: { ar: "نصمم مواقع احترافية لشركات المقاولات تعرض مشاريعك بشكل مبهر وتجذب عملاء جدد.", en: "We design professional construction company websites that showcase your projects impressively and attract new clients." },
    features: [
      { ar: "معرض مشاريع تفاعلي", en: "Interactive project gallery" },
      { ar: "جدول زمني للمشاريع", en: "Project timeline" },
      { ar: "شهادات العملاء", en: "Client testimonials" },
      { ar: "طلب عرض سعر", en: "Quote request form" },
    ],
    faqs: [
      { q: { ar: "هل يمكن عرض المشاريع السابقة؟", en: "Can we showcase previous projects?" }, a: { ar: "نعم، مع صور ومقاطع فيديو وتفاصيل كل مشروع.", en: "Yes, with photos, videos, and details of each project." } },
      { q: { ar: "هل يمكن طلب عرض سعر عبر الموقع؟", en: "Can clients request quotes via the site?" }, a: { ar: "نعم، مع نموذج طلب عرض سعر مفصل.", en: "Yes, with a detailed quote request form." } },
      { q: { ar: "هل يدعم عرض الخدمات المتعددة؟", en: "Does it support multiple services display?" }, a: { ar: "نعم، يمكن إضافة جميع خدمات الشركة مع صفحات مخصصة.", en: "Yes, all company services can be added with dedicated pages." } },
    ],
  },
  {
    slug: "car-showroom-website",
    category: "industry",
    icon: "Car",
    title: { ar: "إنشاء وتصميم موقع معرض سيارات", en: "Car Showroom Website" },
    metaTitle: { ar: "إنشاء وتصميم موقع معرض سيارات في مصر", en: "Car Showroom Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم موقع معرض سيارات احترافي مع نظام عرض وبحث متقدم. اعرض سياراتك أونلاين.", en: "Professional car showroom website with advanced display and search. Showcase your cars online." },
    h1: { ar: "إنشاء وتصميم مواقع معارض السيارات في مصر", en: "Car Showroom Website Design in Egypt" },
    description: { ar: "نصمم مواقع معارض سيارات متطورة مع نظام بحث متقدم وعرض تفاعلي للسيارات.", en: "We design advanced car showroom websites with advanced search and interactive car displays." },
    features: [
      { ar: "بحث متقدم عن السيارات", en: "Advanced car search" },
      { ar: "عرض تفاعلي 360°", en: "360° interactive display" },
      { ar: "مقارنة بين السيارات", en: "Car comparison tool" },
      { ar: "طلب تجربة قيادة", en: "Test drive request" },
    ],
    faqs: [
      { q: { ar: "هل يمكن إضافة سيارات بسهولة؟", en: "Can cars be easily added?" }, a: { ar: "نعم، مع لوحة تحكم متكاملة لإدارة المخزون.", en: "Yes, with a complete dashboard for inventory management." } },
      { q: { ar: "هل يدعم البحث المتقدم؟", en: "Does it support advanced search?" }, a: { ar: "نعم، مع فلاتر حسب الماركة والموديل والسنة والسعر.", en: "Yes, with filters by brand, model, year, and price." } },
      { q: { ar: "هل يمكن طلب تجربة قيادة؟", en: "Can customers request test drives?" }, a: { ar: "نعم، مع نموذج حجز تجربة قيادة.", en: "Yes, with a test drive booking form." } },
    ],
  },
  {
    slug: "social-media-management",
    category: "marketing",
    icon: "Share2",
    title: { ar: "إدارة وسائل التواصل الاجتماعي", en: "Social Media Management" },
    metaTitle: { ar: "إدارة وسائل التواصل الاجتماعي في مصر", en: "Social Media Management in Egypt" },
    metaDesc: { ar: "خدمات إدارة وسائل التواصل الاجتماعي الاحترافية. زيادة التفاعل والمتابعين وتحقيق أهدافك التسويقية.", en: "Professional social media management services. Increase engagement, followers, and achieve your marketing goals." },
    h1: { ar: "خدمات إدارة وسائل التواصل الاجتماعي في مصر", en: "Social Media Management Services in Egypt" },
    description: { ar: "نقدم خدمات إدارة وسائل التواصل الاجتماعي الشاملة من إنشاء المحتوى إلى التحليل والتقارير. نساعدك على بناء حضور قوي على فيسبوك وإنستجرام وتويتر.", en: "We provide comprehensive social media management from content creation to analysis and reporting. We help you build a strong presence on Facebook, Instagram, and Twitter." },
    features: [
      { ar: "إنشاء محتوى إبداعي", en: "Creative content creation" },
      { ar: "جدولة المنشورات", en: "Post scheduling" },
      { ar: "إدارة التفاعلات", en: "Engagement management" },
      { ar: "تقارير أداء شهرية", en: "Monthly performance reports" },
    ],
    faqs: [
      { q: { ar: "كم عدد المنشورات شهريًا؟", en: "How many posts per month?" }, a: { ar: "نقدم خطط متنوعة تبدأ من 12 إلى 30 منشور شهريًا.", en: "We offer various plans from 12 to 30 posts per month." } },
      { q: { ar: "هل تشمل الخدمة التصميم؟", en: "Does the service include design?" }, a: { ar: "نعم، نصمم جميع المنشورات بشكل احترافي.", en: "Yes, we design all posts professionally." } },
      { q: { ar: "هل يمكنني الاطلاع على المحتوى قبل النشر؟", en: "Can I review content before publishing?" }, a: { ar: "نعم، نرسل المحتوى للموافقة قبل النشر.", en: "Yes, we send content for approval before publishing." } },
    ],
  },
  {
    slug: "facebook-ads-management",
    category: "marketing",
    icon: "Megaphone",
    title: { ar: "إدارة إعلانات فيسبوك", en: "Facebook Ads Management" },
    metaTitle: { ar: "إدارة إعلانات فيسبوك في مصر | حملات إعلانية", en: "Facebook Ads Management in Egypt | Ad Campaigns" },
    metaDesc: { ar: "إدارة إعلانات فيسبوك وإنستجرام الاحترافية. حملات مستهدفة تحقق نتائج ملموسة بأقل تكلفة.", en: "Professional Facebook & Instagram ads management. Targeted campaigns with measurable results at minimum cost." },
    h1: { ar: "إدارة إعلانات فيسبوك وإنستجرام في مصر", en: "Facebook & Instagram Ads Management in Egypt" },
    description: { ar: "نقدم خدمات إدارة إعلانات فيسبوك وإنستجرام المتقدمة مع استهداف دقيق وتحسين مستمر لتحقيق أفضل عائد على الاستثمار.", en: "We provide advanced Facebook and Instagram ads management with precise targeting and continuous optimization for the best ROI." },
    features: [
      { ar: "استهداف دقيق للجمهور", en: "Precise audience targeting" },
      { ar: "تصميم إعلانات جذابة", en: "Attractive ad design" },
      { ar: "تحسين مستمر للحملات", en: "Continuous campaign optimization" },
      { ar: "تقارير أداء تفصيلية", en: "Detailed performance reports" },
    ],
    faqs: [
      { q: { ar: "ما هي ميزانية الإعلانات المطلوبة؟", en: "What ad budget is required?" }, a: { ar: "نعمل مع ميزانيات مختلفة ونساعدك في تحديد الميزانية المناسبة.", en: "We work with various budgets and help you determine the right one." } },
      { q: { ar: "كيف تقيسون نجاح الحملة؟", en: "How do you measure campaign success?" }, a: { ar: "من خلال مؤشرات أداء محددة مثل التحويلات والتكلفة لكل عميل.", en: "Through specific KPIs like conversions and cost per acquisition." } },
      { q: { ar: "هل تقدمون تقارير دورية؟", en: "Do you provide regular reports?" }, a: { ar: "نعم، تقارير أسبوعية وشهرية مفصلة.", en: "Yes, detailed weekly and monthly reports." } },
    ],
  },
  {
    slug: "branding-identity-design",
    category: "marketing",
    icon: "Palette",
    title: { ar: "إنشاء وتصميم هوية بصرية", en: "Branding & Identity Design" },
    metaTitle: { ar: "إنشاء وتصميم هوية بصرية احترافية في مصر", en: "Professional Branding & Identity Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم هوية بصرية متكاملة تعكس قيم شركتك وتميزها عن المنافسين. شعار، ألوان، وأدوات تسويقية.", en: "Complete branding design reflecting your company values. Logo, colors, and marketing materials." },
    h1: { ar: "إنشاء وتصميم هوية بصرية متكاملة لشركتك", en: "Complete Brand Identity Design for Your Company" },
    description: { ar: "نصمم هويات بصرية متكاملة تعكس قيم وشخصية شركتك وتميزك عن المنافسين في السوق المصري.", en: "We design complete brand identities that reflect your company values and personality, setting you apart from competitors in the Egyptian market." },
    features: [
      { ar: "تصميم شعار احترافي", en: "Professional logo design" },
      { ar: "دليل الهوية البصرية", en: "Brand guidelines" },
      { ar: "تصميم أدوات تسويقية", en: "Marketing materials design" },
      { ar: "هوية رقمية متكاملة", en: "Complete digital identity" },
    ],
    faqs: [
      { q: { ar: "ماذا تشمل الهوية البصرية؟", en: "What does brand identity include?" }, a: { ar: "شعار، ألوان، خطوط، بطاقات عمل، ورق مراسلات، وأدوات تسويقية.", en: "Logo, colors, fonts, business cards, letterhead, and marketing materials." } },
      { q: { ar: "كم يستغرق تصميم الهوية؟", en: "How long does branding take?" }, a: { ar: "عادة من 2 إلى 4 أسابيع حسب نطاق المشروع.", en: "Usually 2 to 4 weeks depending on project scope." } },
      { q: { ar: "هل يمكن تعديل التصميم؟", en: "Can the design be revised?" }, a: { ar: "نعم، نقدم عدة جولات من التعديلات حتى الرضا التام.", en: "Yes, we offer several revision rounds until complete satisfaction." } },
    ],
  },
  {
    slug: "content-writing-services",
    category: "marketing",
    icon: "PenTool",
    title: { ar: "خدمات كتابة المحتوى", en: "Content Writing Services" },
    metaTitle: { ar: "خدمات كتابة المحتوى في مصر | محتوى تسويقي", en: "Content Writing Services in Egypt | Marketing Content" },
    metaDesc: { ar: "خدمات كتابة محتوى تسويقي احترافي ومحسّن لمحركات البحث. مقالات، نصوص إعلانية، ومحتوى مواقع.", en: "Professional SEO-optimized content writing. Articles, ad copy, and website content." },
    h1: { ar: "خدمات كتابة المحتوى التسويقي الاحترافي", en: "Professional Marketing Content Writing Services" },
    description: { ar: "نقدم خدمات كتابة محتوى تسويقي احترافي ومحسّن لمحركات البحث بالعربية والإنجليزية.", en: "We provide professional, SEO-optimized marketing content writing in Arabic and English." },
    features: [
      { ar: "محتوى محسّن لـ SEO", en: "SEO-optimized content" },
      { ar: "كتابة مقالات ومدونات", en: "Article & blog writing" },
      { ar: "نصوص إعلانية", en: "Ad copywriting" },
      { ar: "محتوى وسائل التواصل", en: "Social media content" },
    ],
    faqs: [
      { q: { ar: "هل المحتوى محسّن لمحركات البحث؟", en: "Is the content SEO-optimized?" }, a: { ar: "نعم، جميع المحتوى يتم تحسينه للكلمات المفتاحية المستهدفة.", en: "Yes, all content is optimized for targeted keywords." } },
      { q: { ar: "هل تكتبون بالعربية والإنجليزية؟", en: "Do you write in Arabic and English?" }, a: { ar: "نعم، لدينا فريق متخصص في الكتابة بكلتا اللغتين.", en: "Yes, we have a team specialized in writing in both languages." } },
      { q: { ar: "ما هي المدة المطلوبة للتسليم؟", en: "What's the delivery time?" }, a: { ar: "عادة من 3 إلى 7 أيام عمل حسب حجم المشروع.", en: "Usually 3 to 7 business days depending on project size." } },
    ],
  },
  {
    slug: "marketing-plan-creation",
    category: "marketing",
    icon: "Target",
    title: { ar: "إعداد خطة تسويقية", en: "Marketing Plan Creation" },
    metaTitle: { ar: "إعداد خطة تسويقية في مصر | استراتيجية تسويق", en: "Marketing Plan Creation in Egypt | Marketing Strategy" },
    metaDesc: { ar: "إعداد خطط تسويقية شاملة ومدروسة لتحقيق أهداف عملك. استراتيجيات مبنية على بيانات وتحليل السوق.", en: "Comprehensive, data-driven marketing plans to achieve your business goals. Strategies built on data and market analysis." },
    h1: { ar: "إعداد خطط تسويقية شاملة لنمو عملك", en: "Comprehensive Marketing Plans for Your Business Growth" },
    description: { ar: "نعد خططًا تسويقية شاملة مبنية على تحليل السوق والمنافسين لتحقيق أهدافك التجارية.", en: "We create comprehensive marketing plans based on market and competitor analysis to achieve your business goals." },
    features: [
      { ar: "تحليل السوق والمنافسين", en: "Market & competitor analysis" },
      { ar: "استراتيجية قنوات التسويق", en: "Marketing channels strategy" },
      { ar: "خطة محتوى متكاملة", en: "Complete content plan" },
      { ar: "مؤشرات أداء قابلة للقياس", en: "Measurable KPIs" },
    ],
    faqs: [
      { q: { ar: "ماذا تشمل الخطة التسويقية؟", en: "What does the marketing plan include?" }, a: { ar: "تحليل السوق، تحديد الجمهور المستهدف، استراتيجية القنوات، وخطة المحتوى.", en: "Market analysis, target audience, channel strategy, and content plan." } },
      { q: { ar: "كم تستغرق إعداد الخطة؟", en: "How long does plan preparation take?" }, a: { ar: "عادة من أسبوع إلى أسبوعين.", en: "Usually one to two weeks." } },
      { q: { ar: "هل تساعدون في تنفيذ الخطة؟", en: "Do you help implement the plan?" }, a: { ar: "نعم، نقدم خدمات تنفيذ ومتابعة الخطة التسويقية.", en: "Yes, we provide plan implementation and follow-up services." } },
    ],
  },
  {
    slug: "website-redesign-services",
    category: "web-design",
    icon: "RefreshCw",
    title: { ar: "إعادة إنشاء وتصميم المواقع", en: "Website Redesign Services" },
    metaTitle: { ar: "إعادة إنشاء وتصميم المواقع في مصر | تحديث موقعك", en: "Website Redesign Services in Egypt | Update Your Site" },
    metaDesc: { ar: "خدمات إعادة إنشاء وتصميم المواقع لتحديث شكل ووظائف موقعك. تصميم عصري وتجربة مستخدم محسّنة.", en: "Website redesign services to update your site's look and functionality. Modern design and improved UX." },
    h1: { ar: "خدمات إعادة إنشاء وتصميم وتطوير المواقع", en: "Website Redesign & Development Services" },
    description: { ar: "نعيد تصميم موقعك بشكل عصري ومحسّن لتجربة المستخدم ومحركات البحث. تحديث كامل للتصميم والأداء.", en: "We redesign your website with modern, UX-optimized and SEO-friendly design. Complete design and performance update." },
    features: [
      { ar: "تحليل الموقع الحالي", en: "Current site analysis" },
      { ar: "تصميم عصري جديد", en: "Modern new design" },
      { ar: "تحسين تجربة المستخدم", en: "UX improvement" },
      { ar: "الحفاظ على ترتيب SEO", en: "SEO ranking preservation" },
    ],
    faqs: [
      { q: { ar: "هل سأفقد ترتيبي في جوجل؟", en: "Will I lose my Google ranking?" }, a: { ar: "لا، نحافظ على ترتيبك من خلال إعادة توجيه صحيحة وتحسين SEO.", en: "No, we preserve your ranking through proper redirects and SEO optimization." } },
      { q: { ar: "كم يستغرق إعادة التصميم؟", en: "How long does a redesign take?" }, a: { ar: "عادة من 3 إلى 8 أسابيع حسب حجم الموقع.", en: "Usually 3 to 8 weeks depending on site size." } },
      { q: { ar: "هل يمكن الاحتفاظ بالمحتوى القديم؟", en: "Can old content be preserved?" }, a: { ar: "نعم، نحافظ على المحتوى الجيد ونحسّن ما يحتاج تحسين.", en: "Yes, we preserve good content and improve what needs improvement." } },
    ],
  },
  {
    slug: "website-speed-optimization",
    category: "technical",
    icon: "Zap",
    title: { ar: "تحسين سرعة المواقع", en: "Website Speed Optimization" },
    metaTitle: { ar: "تحسين سرعة المواقع في مصر | تسريع الموقع", en: "Website Speed Optimization in Egypt" },
    metaDesc: { ar: "خدمات تحسين سرعة المواقع وأدائها. نتائج سريعة في Google PageSpeed وCore Web Vitals.", en: "Website speed and performance optimization. Fast results in Google PageSpeed and Core Web Vitals." },
    h1: { ar: "خدمات تحسين سرعة وأداء المواقع", en: "Website Speed & Performance Optimization Services" },
    description: { ar: "نحسّن سرعة موقعك بشكل ملموس ونضمن اجتياز معايير Core Web Vitals من جوجل.", en: "We significantly improve your website speed and ensure passing Google's Core Web Vitals standards." },
    features: [
      { ar: "تحسين Core Web Vitals", en: "Core Web Vitals optimization" },
      { ar: "ضغط الصور والملفات", en: "Image & file compression" },
      { ar: "تحسين الكاش", en: "Cache optimization" },
      { ar: "تقليل وقت التحميل", en: "Load time reduction" },
    ],
    faqs: [
      { q: { ar: "كم يمكن تحسين السرعة؟", en: "How much can speed be improved?" }, a: { ar: "عادة نحسن السرعة بنسبة 50% إلى 80% حسب الموقع.", en: "We typically improve speed by 50% to 80% depending on the site." } },
      { q: { ar: "هل التحسين يؤثر على التصميم؟", en: "Does optimization affect design?" }, a: { ar: "لا، نحسّن الأداء دون التأثير على التصميم أو الوظائف.", en: "No, we optimize performance without affecting design or functionality." } },
      { q: { ar: "ما هي أدوات القياس المستخدمة؟", en: "What measurement tools are used?" }, a: { ar: "نستخدم Google PageSpeed Insights وGTmetrix وLighthouse.", en: "We use Google PageSpeed Insights, GTmetrix, and Lighthouse." } },
    ],
  },
  {
    slug: "website-maintenance-services",
    category: "technical",
    icon: "Wrench",
    title: { ar: "صيانة المواقع", en: "Website Maintenance Services" },
    metaTitle: { ar: "خدمات صيانة المواقع في مصر | دعم فني", en: "Website Maintenance Services in Egypt | Technical Support" },
    metaDesc: { ar: "خدمات صيانة ودعم فني مستمر للمواقع. تحديثات أمنية، نسخ احتياطية، ومراقبة الأداء.", en: "Continuous website maintenance and technical support. Security updates, backups, and performance monitoring." },
    h1: { ar: "خدمات صيانة ودعم المواقع الإلكترونية", en: "Website Maintenance & Support Services" },
    description: { ar: "نوفر خدمات صيانة شاملة لموقعك تشمل التحديثات الأمنية والنسخ الاحتياطية ومراقبة الأداء.", en: "We provide comprehensive website maintenance including security updates, backups, and performance monitoring." },
    features: [
      { ar: "تحديثات أمنية دورية", en: "Regular security updates" },
      { ar: "نسخ احتياطية يومية", en: "Daily backups" },
      { ar: "مراقبة الأداء", en: "Performance monitoring" },
      { ar: "دعم فني سريع", en: "Fast technical support" },
    ],
    faqs: [
      { q: { ar: "ما الذي تشمله خدمة الصيانة؟", en: "What does maintenance include?" }, a: { ar: "تحديثات أمنية، نسخ احتياطية، مراقبة أداء، وإصلاح الأخطاء.", en: "Security updates, backups, performance monitoring, and bug fixes." } },
      { q: { ar: "كم مرة يتم عمل نسخ احتياطية؟", en: "How often are backups made?" }, a: { ar: "نسخ احتياطية يومية مع إمكانية الاستعادة في أي وقت.", en: "Daily backups with the ability to restore at any time." } },
      { q: { ar: "هل يشمل تعديلات على الموقع؟", en: "Does it include site modifications?" }, a: { ar: "نعم، نقدم عدد محدد من التعديلات الشهرية حسب الباقة.", en: "Yes, we offer a set number of monthly modifications per plan." } },
    ],
  },
  {
    slug: "wordpress-development",
    category: "technical",
    icon: "Code",
    title: { ar: "تطوير ووردبريس", en: "WordPress Development" },
    metaTitle: { ar: "تطوير مواقع ووردبريس في مصر | WordPress", en: "WordPress Development in Egypt" },
    metaDesc: { ar: "تطوير مواقع ووردبريس احترافية مخصصة. قوالب مخصصة، إضافات، وتحسين الأداء.", en: "Professional custom WordPress development. Custom themes, plugins, and performance optimization." },
    h1: { ar: "خدمات تطوير مواقع ووردبريس الاحترافية", en: "Professional WordPress Development Services" },
    description: { ar: "نطور مواقع ووردبريس احترافية مخصصة بقوالب وإضافات مصممة خصيصًا لاحتياجات عملك.", en: "We develop professional custom WordPress sites with themes and plugins designed specifically for your business needs." },
    features: [
      { ar: "قوالب ووردبريس مخصصة", en: "Custom WordPress themes" },
      { ar: "إضافات مخصصة", en: "Custom plugins" },
      { ar: "تحسين الأداء", en: "Performance optimization" },
      { ar: "دعم ووردبريس متخصص", en: "Specialized WordPress support" },
    ],
    faqs: [
      { q: { ar: "لماذا ووردبريس؟", en: "Why WordPress?" }, a: { ar: "ووردبريس يدعم أكثر من 40% من المواقع عالميًا وسهل الإدارة.", en: "WordPress powers over 40% of websites globally and is easy to manage." } },
      { q: { ar: "هل يمكنني إدارة الموقع بنفسي؟", en: "Can I manage the site myself?" }, a: { ar: "نعم، ووردبريس سهل الاستخدام مع تدريب كامل.", en: "Yes, WordPress is user-friendly with full training provided." } },
      { q: { ar: "هل الموقع آمن؟", en: "Is the site secure?" }, a: { ar: "نعم، نطبق أفضل ممارسات الأمان وتحديثات دورية.", en: "Yes, we apply best security practices and regular updates." } },
    ],
  },
  {
    slug: "shopify-store-setup",
    category: "technical",
    icon: "Store",
    title: { ar: "إعداد متجر شوبيفاي", en: "Shopify Store Setup" },
    metaTitle: { ar: "إعداد متجر شوبيفاي في مصر | Shopify", en: "Shopify Store Setup in Egypt" },
    metaDesc: { ar: "إعداد وتخصيص متجر شوبيفاي احترافي. ابدأ البيع أونلاين بسرعة مع خبرائنا.", en: "Professional Shopify store setup and customization. Start selling online quickly with our experts." },
    h1: { ar: "إعداد وتخصيص متاجر شوبيفاي في مصر", en: "Shopify Store Setup & Customization in Egypt" },
    description: { ar: "نعد ونخصص متاجر شوبيفاي احترافية لبدء البيع أونلاين بسرعة وكفاءة.", en: "We set up and customize professional Shopify stores to start selling online quickly and efficiently." },
    features: [
      { ar: "إعداد المتجر الكامل", en: "Complete store setup" },
      { ar: "تخصيص القالب", en: "Theme customization" },
      { ar: "إعداد بوابات الدفع", en: "Payment gateway setup" },
      { ar: "تدريب على إدارة المتجر", en: "Store management training" },
    ],
    faqs: [
      { q: { ar: "ما هي تكلفة شوبيفاي الشهرية؟", en: "What's Shopify's monthly cost?" }, a: { ar: "تبدأ باقات شوبيفاي من 29 دولار شهريًا.", en: "Shopify plans start at $29 per month." } },
      { q: { ar: "هل يدعم الدفع المحلي؟", en: "Does it support local payments?" }, a: { ar: "نعم، مع تكامل بوابات الدفع المصرية.", en: "Yes, with Egyptian payment gateway integration." } },
      { q: { ar: "هل يمكنني إدارة المتجر بنفسي؟", en: "Can I manage the store myself?" }, a: { ar: "نعم، شوبيفاي سهل الاستخدام مع تدريب كامل.", en: "Yes, Shopify is user-friendly with full training." } },
    ],
  },
  {
    slug: "booking-system-website",
    category: "web-design",
    icon: "CalendarCheck",
    title: { ar: "إنشاء وتصميم موقع حجوزات", en: "Booking System Website" },
    metaTitle: { ar: "إنشاء وتصميم موقع حجوزات في مصر", en: "Booking System Website Design in Egypt | Online Booking" },
    metaDesc: { ar: "إنشاء وتصميم مواقع مع نظام حجز متكامل للعيادات والفنادق والخدمات. حجز أونلاين سهل وسريع.", en: "Website design with integrated booking for clinics, hotels, and services. Easy and fast online booking." },
    h1: { ar: "إنشاء وتصميم مواقع بنظام حجوزات متكامل", en: "Booking System Website Design" },
    description: { ar: "نصمم مواقع مع أنظمة حجز إلكترونية متكاملة للعيادات والفنادق والخدمات المختلفة.", en: "We design websites with integrated booking systems for clinics, hotels, and various services." },
    features: [
      { ar: "نظام حجز مواعيد متكامل", en: "Integrated appointment booking" },
      { ar: "إشعارات تلقائية", en: "Automatic notifications" },
      { ar: "تقويم تفاعلي", en: "Interactive calendar" },
      { ar: "دفع إلكتروني", en: "Online payment" },
    ],
    faqs: [
      { q: { ar: "هل يدعم الحجوزات المتعددة؟", en: "Does it support multiple bookings?" }, a: { ar: "نعم، مع إدارة مواعيد متقدمة ومنع التعارض.", en: "Yes, with advanced scheduling and conflict prevention." } },
      { q: { ar: "هل يرسل تذكيرات تلقائية؟", en: "Does it send automatic reminders?" }, a: { ar: "نعم، عبر البريد الإلكتروني والرسائل النصية.", en: "Yes, via email and SMS." } },
      { q: { ar: "هل يدعم الدفع الأونلاين؟", en: "Does it support online payment?" }, a: { ar: "نعم، مع بوابات دفع متعددة.", en: "Yes, with multiple payment gateways." } },
    ],
  },
  {
    slug: "hospital-website-design",
    category: "industry",
    icon: "Hospital",
    title: { ar: "إنشاء وتصميم موقع مستشفى", en: "Hospital Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع مستشفى في مصر", en: "Hospital Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع مستشفيات احترافية مع أنظمة حجز وملفات أطباء. الحل الأمثل للمستشفيات.", en: "Professional hospital website design with booking systems and doctor profiles. The ideal solution for hospitals." },
    h1: { ar: "إنشاء وتصميم مواقع المستشفيات والمراكز الطبية", en: "Hospital & Medical Center Website Design" },
    description: { ar: "نصمم مواقع مستشفيات شاملة مع أنظمة حجز متقدمة وملفات تعريف الأطباء والأقسام الطبية.", en: "We design comprehensive hospital websites with advanced booking, doctor profiles, and medical department pages." },
    features: [
      { ar: "دليل الأطباء والأقسام", en: "Doctor & department directory" },
      { ar: "نظام حجز متقدم", en: "Advanced booking system" },
      { ar: "بوابة المرضى", en: "Patient portal" },
      { ar: "قسم الطوارئ", en: "Emergency section" },
    ],
    faqs: [
      { q: { ar: "هل يدعم عدة أقسام طبية؟", en: "Does it support multiple departments?" }, a: { ar: "نعم، مع صفحات مخصصة لكل قسم وأطبائه.", en: "Yes, with dedicated pages for each department and its doctors." } },
      { q: { ar: "هل يتكامل مع نظام إدارة المستشفى؟", en: "Does it integrate with hospital management?" }, a: { ar: "نعم، نوفر تكامل مع أنظمة HIS المختلفة.", en: "Yes, we provide integration with various HIS systems." } },
      { q: { ar: "هل يدعم عدة لغات؟", en: "Does it support multiple languages?" }, a: { ar: "نعم، مع دعم كامل للعربية والإنجليزية.", en: "Yes, with full Arabic and English support." } },
    ],
  },
  {
    slug: "startup-website-design",
    category: "web-design",
    icon: "Lightbulb",
    title: { ar: "إنشاء وتصميم موقع ستارت اب", en: "Startup Website Design" },
    metaTitle: { ar: "إنشاء وتصميم موقع ستارت اب في مصر", en: "Startup Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم مواقع شركات ناشئة بأسعار تنافسية. موقع احترافي يجذب المستثمرين والعملاء.", en: "Startup website design at competitive prices. Professional site that attracts investors and clients." },
    h1: { ar: "إنشاء وتصميم مواقع الشركات الناشئة في مصر", en: "Startup Website Design in Egypt" },
    description: { ar: "نصمم مواقع للشركات الناشئة تعكس الابتكار وتجذب المستثمرين والعملاء بأسعار مناسبة.", en: "We design startup websites reflecting innovation that attract investors and clients at affordable prices." },
    features: [
      { ar: "تصميم عصري ومبتكر", en: "Modern innovative design" },
      { ar: "صفحة المستثمرين", en: "Investors page" },
      { ar: "عرض المنتج/الخدمة", en: "Product/service showcase" },
      { ar: "نموذج التسجيل المبكر", en: "Early registration form" },
    ],
    faqs: [
      { q: { ar: "هل الأسعار مناسبة للشركات الناشئة؟", en: "Are prices suitable for startups?" }, a: { ar: "نعم، نقدم باقات خاصة للشركات الناشئة بأسعار تنافسية.", en: "Yes, we offer special packages for startups at competitive prices." } },
      { q: { ar: "هل يمكن التوسع لاحقًا؟", en: "Can it scale later?" }, a: { ar: "نعم، نصمم الموقع ليكون قابلاً للتوسع مع نمو شركتك.", en: "Yes, we design the site to be scalable as your company grows." } },
      { q: { ar: "هل يساعد في جذب المستثمرين؟", en: "Does it help attract investors?" }, a: { ar: "نعم، التصميم الاحترافي يعكس جدية المشروع.", en: "Yes, professional design reflects project seriousness." } },
    ],
  },
  {
    slug: "company-profile-website",
    category: "web-design",
    icon: "FileText",
    title: { ar: "إنشاء وتصميم بروفايل شركة", en: "Company Profile Website" },
    metaTitle: { ar: "إنشاء وتصميم بروفايل شركة في مصر", en: "Company Profile Website Design in Egypt" },
    metaDesc: { ar: "إنشاء وتصميم بروفايل شركة رقمي احترافي يعرض خدماتك ومشاريعك بشكل مبهر.", en: "Professional digital company profile showcasing your services and projects impressively." },
    h1: { ar: "إنشاء وتصميم بروفايل شركة رقمي احترافي", en: "Professional Digital Company Profile Design" },
    description: { ar: "نصمم ملفات تعريفية رقمية احترافية لشركتك تعرض خدماتك وإنجازاتك بشكل مبهر.", en: "We design professional digital company profiles showcasing your services and achievements impressively." },
    features: [
      { ar: "تصميم احترافي جذاب", en: "Attractive professional design" },
      { ar: "عرض الخدمات والمشاريع", en: "Services & projects showcase" },
      { ar: "شهادات العملاء", en: "Client testimonials" },
      { ar: "إحصائيات وأرقام", en: "Statistics & figures" },
    ],
    faqs: [
      { q: { ar: "ما الفرق بين البروفايل والموقع؟", en: "What's the difference between a profile and a website?" }, a: { ar: "البروفايل يركز على تعريف الشركة بينما الموقع أشمل.", en: "A profile focuses on company introduction while a website is more comprehensive." } },
      { q: { ar: "هل يمكن تحميله كـ PDF؟", en: "Can it be downloaded as PDF?" }, a: { ar: "نعم، يمكن توفير نسخة PDF قابلة للتحميل.", en: "Yes, a downloadable PDF version can be provided." } },
      { q: { ar: "هل يدعم عدة لغات؟", en: "Does it support multiple languages?" }, a: { ar: "نعم، بالعربية والإنجليزية.", en: "Yes, in Arabic and English." } },
    ],
  },
  {
    slug: "website-cost-egypt",
    category: "web-design",
    icon: "DollarSign",
    title: { ar: "أسعار إنشاء وتصميم المواقع في مصر", en: "Website Cost in Egypt" },
    metaTitle: { ar: "أسعار إنشاء وتصميم المواقع في مصر 2026", en: "Website Design Prices in Egypt 2026 | Website Cost" },
    metaDesc: { ar: "تعرف على أسعار إنشاء وتصميم المواقع في مصر 2026. مقارنة شاملة للأسعار والخدمات. احصل على أفضل قيمة.", en: "Learn about website design prices in Egypt 2026. Comprehensive price and service comparison. Get the best value." },
    h1: { ar: "دليل أسعار إنشاء وتصميم المواقع في مصر 2026", en: "Website Design Price Guide in Egypt 2026" },
    description: { ar: "دليل شامل لأسعار تصميم المواقع في مصر يساعدك على فهم التكاليف واختيار الحل المناسب لميزانيتك. نقدم أسعارًا تنافسية مع جودة استثنائية.", en: "A comprehensive guide to website design prices in Egypt helping you understand costs and choose the right solution for your budget. We offer competitive prices with exceptional quality." },
    features: [
      { ar: "أسعار شفافة", en: "Transparent pricing" },
      { ar: "باقات متنوعة", en: "Various packages" },
      { ar: "جودة عالية بأسعار منافسة", en: "High quality at competitive prices" },
      { ar: "عروض خاصة", en: "Special offers" },
    ],
    faqs: [
      { q: { ar: "ما هو متوسط سعر تصميم موقع في مصر؟", en: "What's the average website design cost in Egypt?" }, a: { ar: "تتراوح الأسعار حسب نوع الموقع ومتطلباته، تواصل معنا لعرض سعر مخصص.", en: "Prices vary by site type and requirements, contact us for a custom quote." } },
      { q: { ar: "هل هناك تكاليف سنوية؟", en: "Are there annual costs?" }, a: { ar: "نعم، تشمل الاستضافة والنطاق والصيانة.", en: "Yes, including hosting, domain, and maintenance." } },
      { q: { ar: "هل يمكن الدفع بالتقسيط؟", en: "Can I pay in installments?" }, a: { ar: "نعم، نوفر خيارات دفع مرنة تناسب احتياجاتك.", en: "Yes, we offer flexible payment options to suit your needs." } },
    ],
  },
];

export const getServiceBySlug = (slug: string): Service | undefined => {
  return services.find((s) => s.slug === slug);
};

export const getServicesByCategory = (category: string): Service[] => {
  return services.filter((s) => s.category === category);
};
